# Generated by Django 5.1.2 on 2025-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('versione', models.CharField(default='1', max_length=32)),
                ('contenuto', models.TextField()),
                ('ristretto', models.BooleanField(default=False)),
                ('esperienze', models.TextField(blank=True, help_text='Elenco (anche lungo) di avventure già vissute dal personaggio', null=True)),
            ],
            options={
                'unique_together': {('nome', 'versione')},
            },
        ),
    ]
