# Generated by Django 5.1.2 on 2025-08-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='ristretto',
            new_name='inglese',
        ),
    ]
