# Generated by Django 5.1.2 on 2025-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_rename_ristretto_persona_inglese'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ristretto',
            field=models.BooleanField(default=False),
        ),
    ]
